
#Harvest config
[common]
	#Harvest works on netherwart
	netherwart = true
	#The blacklisted crops, these can not be harvested
	blacklist = ["thermal:flax"]
	#Consumes a seed (from the drops) to replant
	consumeSeed = true
	#Use the blacklist as a whitelist instead
	whitelist = false

